version: '3' 

services:
  mysql-router:
    build: ./mysql_router/
    image: trg_mysql_router:1
    container_name: mysql_router
    restart: always
    ports:
      - "6446:6446"
    volumes:
      - ../hosts.txt:/hosts.txt:ro
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD